# Generated by Django 5.2.5 on 2025-10-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userID', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='password',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
