# Generated by Django 5.2.5 on 2025-10-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userID', '0002_userdetails_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='verificationStatus',
            field=models.BooleanField(default=False),
        ),
    ]
