# Generated by Django 5.2.5 on 2025-10-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userID', '0003_userdetails_verificationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profileImage',
            field=models.ImageField(default=1, upload_to='userProfileImages/'),
            preserve_default=False,
        ),
    ]
