# Generated by Django 5.2.5 on 2025-10-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userID', '0005_userkycdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkycdetails',
            name='emailAddress',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
