# Generated by Django 5.2.5 on 2025-10-23 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userID', '0007_useraccountdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('FUNDING', 'Funding'), ('TRANSACTIONS', 'Transactions'), ('CARDS', 'Cards'), ('GENERAL', 'General')], max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Order in which the FAQ should be displayed.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Entry',
                'verbose_name_plural': 'FAQ Entries',
                'ordering': ['order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='CardRelatedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(help_text='Detailed description of the problem.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('RESOLVED', 'Resolved'), ('AWAITING_INFO', 'Awaiting User Information')], default='PENDING', help_text='Current status of the issue.', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Response provided by the admin team.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('issue_category', models.CharField(choices=[('STOLEN', 'Lost or Stolen Card'), ('ACTIVATION', 'Activation/Deactivation Issue'), ('FAILED_TXN', 'Card Transaction Failed'), ('OTHER', 'Other Card Issue')], help_text='Specific category of the card issue.', max_length=50)),
                ('card_reference', models.CharField(blank=True, help_text='Reference/Masked ID of the card involved.', max_length=100, null=True)),
                ('user', models.ForeignKey(help_text='The user who submitted this issue.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixFundingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(help_text='Detailed description of the problem.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('RESOLVED', 'Resolved'), ('AWAITING_INFO', 'Awaiting User Information')], default='PENDING', help_text='Current status of the issue.', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Response provided by the admin team.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, help_text='The amount that was deposited.', max_digits=15, null=True)),
                ('reference_id', models.CharField(help_text='Bank/Payment Gateway Transaction ID or Reference.', max_length=100)),
                ('proof_of_payment', models.TextField(blank=True, help_text='Link or description of proof of payment (e.g., screenshot link).', null=True)),
                ('user', models.ForeignKey(help_text='The user who submitted this issue.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UndeliveredTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(help_text='Detailed description of the problem.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('RESOLVED', 'Resolved'), ('AWAITING_INFO', 'Awaiting User Information')], default='PENDING', help_text='Current status of the issue.', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Response provided by the admin team.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(help_text="Type of transaction (e.g., 'Airtime', 'Data', 'Electricity').", max_length=50)),
                ('recipient_details', models.CharField(help_text='Recipient phone number, meter number, or cable TV ID.', max_length=100)),
                ('transaction_id', models.CharField(help_text='Internal transaction ID from your application.', max_length=100)),
                ('user', models.ForeignKey(help_text='The user who submitted this issue.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
