# Generated by Django 5.2.5 on 2025-10-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userID', '0008_faqentry_cardrelatedissue_fixfundingissue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixfundingissue',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount in question.', max_digits=15, null=True),
        ),
    ]
