# Generated by Django 5.2.5 on 2025-10-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userID', '0009_fixfundingissue_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixfundingissue',
            name='amount',
        ),
        migrations.AddField(
            model_name='undeliveredtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount in question.', max_digits=15, null=True),
        ),
    ]
