# Generated by Django 5.2.5 on 2025-10-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userID', '0010_remove_fixfundingissue_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrelatedissue',
            name='issue_category',
            field=models.CharField(choices=[('Lost or Stolen Card', 'Lost or Stolen Card'), ('Activation/Deactivation Issue', 'Activation/Deactivation Issue'), ('Card Transaction Failed', 'Card Transaction Failed'), ('Other Card Issue', 'Other Card Issue')], help_text='Specific category of the card issue.', max_length=50),
        ),
    ]
