# Generated by Django 5.2.5 on 2025-10-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userID', '0011_alter_cardrelatedissue_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrelatedissue',
            name='issue_description',
            field=models.CharField(blank=True, help_text='Issue description', max_length=300, null=True),
        ),
    ]
