# Generated by Django 5.2.5 on 2025-10-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userID', '0015_webhooklog_userkycdetails_userdob_uservirtualaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkycdetails',
            old_name='userdob',
            new_name='birth_date',
        ),
    ]
