# Generated by Django 5.2.5 on 2025-10-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userID', '0016_rename_userdob_userkycdetails_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkycdetails',
            name='idcard',
            field=models.ImageField(blank=True, null=True, upload_to='userifcardsimages/'),
        ),
        migrations.AlterField(
            model_name='userkycdetails',
            name='utilitybillimage',
            field=models.ImageField(blank=True, null=True, upload_to='utilitybillimages/'),
        ),
    ]
