# Generated by Django 5.2.5 on 2025-10-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userID', '0017_alter_userkycdetails_idcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkycdetails',
            name='passportphotograph',
            field=models.ImageField(blank=True, null=True, upload_to='passportphotographimages/'),
        ),
    ]
