# Generated by Django 5.2.5 on 2026-04-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"Storage": ["64GB"], "Colors": ["Black"]}'),
        ),
    ]
