# Generated by Django 5.2.5 on 2026-04-18 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_product_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_state', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('business_categories', models.JSONField(default=list)),
                ('has_ready_stock', models.BooleanField(default=False)),
                ('fulfillment_time', models.CharField(max_length=100)),
                ('delivery_method', models.CharField(max_length=100)),
                ('product_condition', models.CharField(max_length=50)),
                ('social_media_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('cac_document', models.FileField(blank=True, null=True, upload_to='verifications/cac/')),
                ('valid_id', models.FileField(blank=True, null=True, upload_to='verifications/ids/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Verification',
                'verbose_name_plural': 'Business Verifications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
